/// Represents the role of a participant in a chat conversation.
enum MessageRole {
  /// A message sent by the human user.
  user,

  /// A message generated by the Gemini model.
  model,
}

/// Domain entity representing a single message in a study chat.
///
/// Pure Dart — no Firebase or external imports.
class ChatMessage {
  const ChatMessage({
    required this.id,
    required this.content,
    required this.role,
    required this.timestamp,
    required this.chatId,
    this.imageUrl,
  });

  /// Unique identifier for this message.
  final String id;

  /// Text content of the message.
  final String content;

  /// Who authored this message.
  final MessageRole role;

  /// When the message was created.
  final DateTime timestamp;

  /// The ID of the chat session this message belongs to.
  final String chatId;

  /// Optional URL of an image attached to this message.
  final String? imageUrl;

  /// Returns a copy of this message with the given fields replaced.
  ChatMessage copyWith({
    String? id,
    String? content,
    MessageRole? role,
    DateTime? timestamp,
    String? chatId,
    String? imageUrl,
    bool clearImageUrl = false,
  }) {
    return ChatMessage(
      id: id ?? this.id,
      content: content ?? this.content,
      role: role ?? this.role,
      timestamp: timestamp ?? this.timestamp,
      chatId: chatId ?? this.chatId,
      imageUrl: clearImageUrl ? null : (imageUrl ?? this.imageUrl),
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          role == other.role &&
          timestamp == other.timestamp &&
          chatId == other.chatId &&
          imageUrl == other.imageUrl;

  @override
  int get hashCode =>
      Object.hash(id, content, role, timestamp, chatId, imageUrl);

  @override
  String toString() => 'ChatMessage('
      'id: $id, '
      'role: $role, '
      'chatId: $chatId, '
      'timestamp: $timestamp, '
      'content: ${content.length > 40 ? '${content.substring(0, 40)}…' : content}'
      ')';
}
